server:
    port: 8724
    shutdown: graceful


spring:
    profiles:
        active: local
        group:
          local:
              - console-logging # 콘솔 로깅만 사용
          test:
              - console-logging
              - file-logging # 파일 로깅 사용
          prod:
              - console-logging
              - file-logging # 파일 로깅 사용

#    config: include 사용하기 위한 레거시 사용 플래그
#        use-legacy-processing: true

token:
    access-expired-time: 3600
    refresh-expired-time: 604800
    jwt-key: LNS2CR13KJ7JYB03FNGX8TP73X9KYWOA

