#LOG
logging:
    file:
        name: ./logs/web-chat.log
    level:
        com.kr.formdang: debug
        jdbc.sqltiming: info #SQL 문과 이 SQL 문을 수행하는 시간(ms)을 같이 보여준다.
        jdbc.result-settable: info #SQL 의 결과로 조회된 데이터를 table 형태로 로그를 보여준다.
        http.logging: info


spring:
    session:
        store-type: redis
    redis:
        host: localhost
        port: 6379
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: admin
            database: formdang-chat