spring:
#    profiles: 예전 사용 방식
#        include:
#            - console-logging
    session:
        store-type: redis
    redis:
        host: localhost
        port: 6379
    data:
        mongodb:
            host: localhost
            port: 27017
            database: formdang-chat
